ALTER TABLE jobs ADD COLUMN latitude NUMERIC(10, 7);
ALTER TABLE jobs ADD COLUMN longitude NUMERIC(10, 7);

ALTER TABLE leads ADD COLUMN latitude NUMERIC(10, 7);
ALTER TABLE leads ADD COLUMN longitude NUMERIC(10, 7);